server:
  port: 9090

spring:
  application:
    name: gateway-service

  cloud:
    sentinel:
      eager: true
      transport:
        port: 8719
        dashboard: 127.0.0.1:8070

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true # gateway 可以从 nacos 发现微服务

#图形化展示配置
management:
  endpoints:
    web:
      exposure:
        include: '*'  #监控